name: React a hosting

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar build
        run: npm run build
      
      - name: Desplegar vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          ftp-server: ftp://myccontadores.cl
          ftp-username: github@myccontadores.cl
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
